### ISSUE TITLE
Ajouter une image de mise en avant article stockée sur cloud

### ISSUE THREAD

**Issue by Eline31** [fabmob/fabmob.io#40]
J'ai tenté d'ajouter une image de mise en avant dans l'article sur la démobilité en l'ajoutant d'abord dans un dossier image par son lien cloud étant stockée sur cloud puis en ajoutant dans l'article le nom de l'image enregistrée sur github. Elle est apparue pendant quelques minutes puis a disparu. L'article et l'image sont stocké dans le dossier 'articles' puis '2021'.
J'ai remarqué que beaucoup d'images avaient une même URL imgur.com, faut-il les stocker là-dessus pour pouvoir les faire apparaître dans nos articles ?

**Comment by laem** [comment]
J'ai corrigé et ajouté la doc :) 

doc : https://github.com/fabmob/fabmob.io/commit/e80eeaca7b70c6ef72be937f0b514d0d396197c2

**Comment by laem** [comment]
N'hésite pas à rouvrir cette issue si c'est pas clair
