### ISSUE TITLE
Articles - passage à la ligne au tiret pour les dialogues

### ISSUE THREAD

**Issue by Eline31** [fabmob/fabmob.io#58]
Malgré une mise en page travaillée pour passer à la ligne à chaque tiret, ils se suivent dans le texte et ne comprend pas le passage à la ligne avec les tirets - à voir sur l'article Psycho-déambulation.

**Comment by laem** [comment]
Tu peux me montrer la ligne précise par exemple où ça ne marche pas ? Quand tu ouvres un fichier sur github, tu cliques sur le numéro de ligne dans la marge et ça te donne une URL précise vers cette ligne.

**Comment by Eline31** [comment]
Les problèmes commencent entre les lignes 25 et 27, là où les dialogues commencent. Malgré tes instructions, je n'arrive pas à obtenir d'URL de la ligne...

**Comment by laem** [comment]
Ah oui merde mes instructions ne marchent pas pour les fichiers markdown :laughing:

**Comment by laem** [comment]
@Eline31 c'est corrigé, dis-moi si c'est bien

**Comment by Eline31** [comment]
C'est parfait ! C'est automatique du coup et valable pour les prochains textes contenant des dialogues ?
