### ISSUE TITLE
Date dans le dernier article

### ISSUE THREAD

**Issue by laem** [fabmob/fabmob.io#59]
@Eline31 dans ton dernier article, en guise de `date` tu n'as mis que l'année, pas la date complète. 
le problème vient de là.
Tu peux regarder ce qui est fait ici par exmple : https://github.com/fabmob/fabmob.io/blob/master/contenu/articles/2020/psycho-déambulation.md

**Comment by Eline31** [comment]
D'accord, je pensais que ça ne poserait pas de problème, mais dans ce cas je donne la date de publication ?
