### ISSUE TITLE
Compléter la page Tracemob

### ISSUE THREAD

**Issue by laem** [fabmob/fabmob.io#65]
- [x] faire une page d'accueil de type appli pas trop moche
- [x] réintégrer le contenu de https://oultim.frama.site ici, le .md est dans /admin
- [x] le faire un peu joliment, du CSS et un tri par date
- [ ] intégrer les images ?
- [x] faire du chargement fainéant pour cette page, qui ne doit pas alourdir le reste du site
- [x] faire un dossier tracemob et plusieurs composants
- [x] https://lafabriquedesmobilites.fr/communs clic sur tracemob -> /tracemob
- [x] intégrer un lien clair vers les CGU
- [ ] parler du contexte de l'app, agremob, un encart coachCO2

@PatGendre je vais m'en charger dès que possible

**Comment by PatGendre** [comment]
merci @laem :-)
Super pour ce 1er jet, comme Romain, je dirais que c'est bien au-delà de ce que j'aurais pu faire!

J'ai corrigé qq micro-coquilles + ajout mention de e-mission directement dans master car la modif ne me semble pas risquée. Mais je ne peux pas vérifier en direct car je suppose que la mise à jour sur netlify n'est pas instantanée?

Sinon quelques commentaires aussi à discuter avec Gabriel et Romain :  
- les textes en bleu ne sont pas cliquables, cette couleur incite à essayer de cliquer
- certains textes correspondent à l'expé la Rochelle mais pas au fonctionnement actuel de l'appli (dès qu'elle sera publiée), j'aurais tendance à être moins "vendeur" et à **nettement séparer ce que l'appli fait d'une part, ce qu'elle pourrait faire d'autre part**, exemples :  
- vous pourrez envoyer vos données de déplacement moyennées et anonymisées à votre collectivité
- envoyées sur votre entrepôt de données personnelles
- seulement si vous le voulez, faites un don

**Comment by PatGendre** [comment]
merci @laem , super!
idéalement:
- ce serait bien une URL anchor pour chaque ancienne page du site frama
- il faudrait reprendre la page livrable pour donner accès aux docs, éventuellement les stocker sur le site ; sur ce point je peux t'aider bien sûr
- est-ce que les articles sont dans l'ordre ante-chrono? est-ce qu'on pourrait ajouter leur date? (comme ça on saurait ;-)

Dis moi si je peux contribuer pour finaliser!

**Comment by laem** [comment]
Je te réponds sur #71
