### ISSUE TITLE
Page tracemob v3

### ISSUE THREAD

**Issue by laem** [fabmob/fabmob.io#71]
- [ ] intégrer les images des articles d'archive ? elles sont dans les fichiers, mais pas affichées encore. Est-ce nécessaire ?
- [ ] bien trier les articles d'archive : il sufit d'ajouter le bon nombre à deux chiffres en début de nom de fichier. C'est le cas pour certains mais pas tous @PatGendre 
- [ ] parler du contexte de l'app, agremob, un encart coachCO2

@PatGendre j'ai reglé la plupart des tâches restantes, dont l'intégration de l'archive. Je l'ai fait de façon sommaire, n'hésite pas à faire de retours ici.

Cette issue fait suite à #65

**Comment by laem** [comment]
Autres suggestions de @PatGendre sur l'ancienne issue.

- [ ] ajouter la date aux articles

Alors le problème c'est que la date n'est pas sur la plupart des articles, dans les métadonnées des fichiers .md. @PatGendre tu peux les ajouter ? Il faut juste nommer l'attribut "date" et mettre un format de date régulier (par exemple 01/02/2021). C'est ici https://github.com/fabmob/fabmob.io/tree/master/contenu/tracemob-archive

- [ ] ce serait bien une URL anchor pour chaque ancienne page du site frama

Bonne idée.

- [ ] il faudrait reprendre la page livrable pour donner accès aux docs, éventuellement les stocker sur le site ; sur ce point je peux t'aider bien sûr

J'ai ajouté la page 'livrables finaux". Pour les docs, peut-être que le mieux est de mettre un fichier zip sur cloud.fabmob.io ?

**Comment by PatGendre** [comment]
> intégrer les images des articles d'archive ?

Non pas indispensable

**Comment by PatGendre** [comment]
> URL anchor

Les ancres ne marchent pas forcément quand je copie-colle l'URL dans un navigateur
exemple https://lafabriquedesmobilites.fr/tracemob#14.lancement-des-tests-phase-2
A re-vérifier

**Comment by laem** [comment]
> Les ancres ne marchent pas forcément quand je copie-colle l'URL dans un navigateur
exemple https://lafabriquedesmobilites.fr/tracemob#14.lancement-des-tests-phase-2
> A re-vérifier

Quel est ton problème exactement ? Chez moi ça fonctionne.

Pour les articles (ajout de dates, suppression, changement des liens vers des PDF, etc), tu as la main dessus :) 
C'est ici https://github.com/fabmob/fabmob.io/tree/master/contenu/tracemob-archive

Pour les PDFs, le plus simple me semble en effet de mettre un PDF dans un cloud. Je n'ai mis en place l'hébergement de fichier seulement pour les images pour l'instant.

**Comment by laem** [comment]
@PatGendre je t'ai invité avec les droits d'écriture sur ce dépot pour que tu n'aies pas à forker. Il faudra faire une Pull Request par contre

**Comment by PatGendre** [comment]
@laem  merci j'ai créé les PRs

Les ancres ont l'air de marcher, c'était peut être un pb de cache ou ce genre de choses.

> Pour les PDFs, le plus simple me semble en effet de mettre un PDF dans un cloud. 
Oui je pensais mettre sur Google Cloud

**Comment by PatGendre** [comment]
@laem tiens moi au courant quand tu auras pu mettre à jour la page, merci :-)

**Comment by PatGendre** [comment]
salut @laem oui c'était un peu fastidieux, mais ça m'a paru plus "naturel", même pour toi ensuite pour committer...
j'aurais dû faire ça sous git au lieu de l'ihm...
Pour la prochaine fois ;-)

**Comment by PatGendre** [comment]
bonjour @laem quand prévois-tu de mettre à jour les pages "historiques" du projet traceur : ajout de la date et classement anti-chrono ?

**Comment by laem** [comment]
C'est fait :)
